"use client";
import React, { useEffect } from "react";
import ChapterCard from "./Chapter";

interface Thumbnail {
  url: string;
  width: number;
  height: number;
}

interface Chapter {
  title: string;
  time: number;
  thumbnails: Thumbnail[];
}

interface Chapters {
  areAutoGenerated: boolean;
  chapters: Chapter[];
}

interface VideoData {
  id: string;
  duration: number;
  title: string;
  chapters: Chapters;
}
export default function ChapterList({
  data,
  duration,
  videoId,
}: {
  data: any;
  duration: number;
  videoId: string;
}) {
  return (
    <div className="p-4 flex flex-col gap-2">
      {data.chapters.chapters.map((chapter: any, index: number, arr: any) => (
        <ChapterCard
          title={chapter.title}
          videoId={videoId}
          thumbnails={chapter.thumbnails[0].url}
          timeStamp={chapter.time}
          key={chapter.title}
          nextTimestamp={arr[index + 1]?.time}
          lastTimestamp={arr[index - 1]?.time}
          totalDuration={duration}
          chapterIndex={index}
          totalChapters={arr.length}
        />
      ))}
    </div>
  );
}
