import Chaptersidebar from "@/app/_component/Chaptersidebar";
import VideoPlayer from "@/app/_component/VideoPlayer";
import { getVideoInfo } from "@/app/utils";
import React from "react";

interface Thumbnail {
  url: string;
  width: number;
  height: number;
}

interface Chapter {
  title: string;
  time: number;
  thumbnails: Thumbnail[];
}

interface Chapters {
  areAutoGenerated: boolean;
  chapters: Chapter[];
}

interface VideoData {
  id: string;
  duration: number;
  title: string;
  chapters: Chapters;
}

async function getDuration(videoId: string): Promise<number> {
  const res = await fetch(
    `https://yt.lemnoslife.com/videos?part=contentDetails&id=${videoId}`,
    { cache: "no-store" }
  );
  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }
  const data = await res.json();
  return data.items[0]?.contentDetails?.duration || 0;
}

export default async function Page({ params }: { params: { slug: string } }) {
  const data: VideoData = await getVideoInfo(params.slug);
  const duration = await getDuration(params.slug);

  console.log("---", data, duration);
  return (
    <div className="flex flex-row gap-2 max-h-screen h-screen overflow-hidden bg-[#292929]">
      <div className="flex flex-col gap-2 w-3/4 overflow-y-auto">
        <VideoPlayer />
      </div>
      <div className="flex flex-col gap-2 w-1/4 overflow-y-auto">
        <Chaptersidebar data={data} duration={duration} videoId={params.slug} />
      </div>
    </div>
  );
}
